# Generated by Django 3.1.5 on 2021-01-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toinkerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toinkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
